<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Getting Started with PHP on Codemason</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                margin:0px; 
                padding:0px;
                height: 100vh;
                background: #5D6CB1;
                font-family: "Open Sans", Helvetica, Arial, sans-serif;
            }

            .flex-center {
                height: 100vh;
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .container {
                width:580px; 
                overflow:hidden; 
                margin: 0 auto; 
                text-align: center;
                padding: 0px 20px 0px 20px;
            }

            .title {
                font-size:50px;
                font-family: 'Luckiest Guy', cursive;
                color:#fff;
                margin-bottom: 20px;
            }

            .panel {
                padding:30px 0px 30px 0px; 
                background-color:#ffffff; 
                box-shadow: 0 9px 20px 0px rgba(0,0,0,0.05); 
                -webkit-box-shadow: 0 9px 20px 0px rgba(0,0,0,0.05);
                border-radius: 5px;
            }

            .panel h1 {
                font-family: "Open Sans", Helvetica, Arial, sans-serif;
                font-size: 25px;
                margin-top: 8px;
                margin-bottom: 8px;
                color: #54585e;
                -webkit-font-smoothing: antialiased;
                font-weight: 300;
                line-height: 1.4;
            }

            .footer {
                margin-top:30px;
            }
            .footer a {
                color: #cacaca;
                padding: 0 30px;
                font-size: xx-small;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
                margin-top:20px;
            }

            .footer a:hover {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
    <div class="flex-center">
            <div class="container">
                <h1 class="title">Quote Rotator.</h1>
                <div class="panel">
                    <h1><i><?php echo $quote; ?></i></h1>
                </div>

                <div class="footer">
                    <a href="http://mason.ci/">Codemason</a>
                    <a href="http://mason.ci/docs">Documentation</a>
                    <a href="https://github.com/codemasonhq">GitHub</a>
                    <a href="https://twitter.com/codemasonhq">Twitter</a>
                </div>

            </div>
        </div>
    </body>
</html>